experiment:
  name: "Climate change"
  version: "1.0.0"
  description: "Modeling Swiss farmer's attitudes about climate change."
  dataset_url: "https://www.research-collection.ethz.ch/bitstreams/42a2f58b-d925-4352-908f-91db854466a1/download"
  dataset_file_name: "dataset.csv"
  dataset_folder: "data"
  dataset_file_path: "data/dataset.csv"
  dataset_file_preprocessed: "data/dataset_preprocessed.csv"