name: climate-analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run climate analysis pipeline
        run: |
          set -e
          echo "Running training script..."
          python src/train.py
          ls -lh output_metrics.json summary_plot.png

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          
          # Verificar se os arquivos existem
          if [ ! -f output_metrics.json ]; then
            echo "Error: output_metrics.json not found"
            exit 1
          fi
          if [ ! -f summary_plot.png ]; then
            echo "Error: summary_plot.png not found"
            exit 1
          fi

              echo "# Climate Analysis Report" > report.md
              echo "" >> report.md
              echo "## Summary Plot" >> report.md
              echo "" >> report.md
              echo "![](./summary_plot.png)" >> report.md
              echo "" >> report.md
              echo "## Output Metrics" >> report.md
              echo "" >> report.md
              echo '```' >> report.md
              cat output_metrics.json >> report.md
              echo '```' >> report.md

              cml comment create report.md