name: climate-analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc3-base1
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run climate analysis pipeline
        run: |
          set -e
          echo "Running training script..."
          python src/train.py
          ls -lh output_metrics.json summary_plot.png

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          
          # Check required files
          if [ ! -f output_metrics.json ]; then
            echo "Error: output_metrics.json not found"
            exit 1
          fi
          if [ ! -f summary_plot.png ]; then
            echo "Error: summary_plot.png not found"
            exit 1
          fi

          # ✅ Criar arquivo markdown primeiro
          cat > report.md << EOF
# Climate Analysis Report

\`\`\`json
$(cat output_metrics.json)
\`\`\`

## Summary Plot
![](./summary_plot.png)
EOF

          # ✅ Usar o arquivo criado como argumento
          cml comment create report.md